import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import{supabase}from'./supabase';import'./admin.css';
const box={background:'#fff',border:'1px solid #eadfd3',borderRadius:16,padding:20,marginBottom:16};
function Admin(){const[user,setUser]=useState(null),[role,setRole]=useState(null),[status,setStatus]=useState('Checking access…'),[products,setProducts]=useState([]),[uploading,setUploading]=useState(false),[uploadError,setUploadError]=useState(''),[uploadedImageUrl,setUploadedImageUrl]=useState(''),[editing,setEditing]=useState(null),[saving,setSaving]=useState(false);
const load=async()=>{const{data,error}=await supabase.from('products').select('*').order('id');if(error)setUploadError(error.message);else setProducts(data||[])};
useEffect(()=>{(async()=>{const{data:{session}}=await supabase.auth.getSession();if(!session){setStatus('Not logged in');return}setUser(session.user);const{data,error}=await supabase.from('admins').select('role').eq('user_id',session.user.id).single();if(error||!data){setRole('user');setStatus('Access denied - not an admin');return}setRole(data.role);setStatus('Access granted')})()},[]);
useEffect(()=>{if(role==='admin')load()},[role]);
const upload=async e=>{const f=e.target.files?.[0];if(!f)return;if(!f.type.startsWith('image/'))return setUploadError('Please select an image');if(f.size>5*1024*1024)return setUploadError('Image must be under 5MB');setUploading(true);setUploadError('');try{const path=`product-images/${Date.now()}-${f.name.replace(/\s+/g,'-')}`;const{error}=await supabase.storage.from('product-images').upload(path,f);if(error)throw error;const{data}=supabase.storage.from('product-images').getPublicUrl(path);setUploadedImageUrl(data.publicUrl)}catch(e){setUploadError(e.message)}finally{setUploading(false)}};
const add=async e=>{e.preventDefault();if(!uploadedImageUrl)return setUploadError('Please upload an image first');const f=e.currentTarget;setSaving(true);try{const{error}=await supabase.from('products').insert({name:f.name.value,price:Number(f.price.value),stock:Math.max(0,Number(f.stock.value)),image:uploadedImageUrl,description:f.description.value});if(error)throw error;f.reset();setUploadedImageUrl('');setStatus('Product added successfully');await load()}catch(e){setUploadError(e.message)}finally{setSaving(false)}};
const save=async p=>{setSaving(true);try{const{error}=await supabase.from('products').update({price:Number(p.editPrice),stock:Math.max(0,Number(p.editStock))}).eq('id',p.id);if(error)throw error;setProducts(x=>x.map(a=>a.id===p.id?{...a,price:Number(p.editPrice),stock:Math.max(0,Number(p.editStock))}:a));setEditing(null);setStatus('Price & stock updated')}catch(e){setUploadError(e.message)}finally{setSaving(false)}};
const del=async id=>{if(!confirm('Delete this product?'))return;const{error}=await supabase.from('products').delete().eq('id',id);if(error)setUploadError(error.message);else{setProducts(x=>x.filter(p=>p.id!==id));setStatus('Product deleted')}};
if(!user)return <div className="admin-gate"><div className="admin-card"><h1>Poojan Paradise Admin</h1><p>{status}</p></div></div>;if(role!=='admin')return <div className="admin-gate"><div className="admin-card"><h1>Access Denied</h1><p>Admin account required.</p></div></div>;
return <div style={{minHeight:'100vh',background:'#f7f3ed',padding:'28px 18px',color:'#2d2118'}}><main style={{maxWidth:1100,margin:'auto'}}><header style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,marginBottom:20}}><div><div style={{fontSize:12,letterSpacing:2,color:'#a06a20',fontWeight:700}}>POOJAN PARADISE</div><h1 style={{margin:'5px 0'}}>Admin Panel</h1><span>{user.email}</span></div><button onClick={()=>supabase.auth.signOut()}>Logout</button></header><div style={{...box,background:'#fffaf0'}}><b>Price + Stock Control</b><p style={{marginBottom:0}}>Yahan se product ka price aur stock quantity change karo. Stock 0 hote hi website par Out of Stock status use kiya ja sakta hai.</p></div>{status&&<div style={{...box,padding:12}}>{status}</div>}{uploadError&&<div style={{...box,color:'#9b1c1c'}}>{uploadError}</div>}
<section style={box}><h2>Products</h2>{products.length===0?<p>No products found.</p>:products.map(p=><div key={p.id} style={{display:'grid',gridTemplateColumns:'70px 1fr auto',gap:14,alignItems:'center',padding:'14px 0',borderTop:'1px solid #eee5dc'}}>{p.image?<img src={p.image} alt={p.name} style={{width:70,height:70,objectFit:'contain',borderRadius:10}}/>:<div/>}<div><b>{p.name}</b><div style={{marginTop:5}}>₹{Number(p.price).toFixed(2)} &nbsp; • &nbsp; <b style={{color:p.stock>0?'#237a35':'#b42318'}}>{p.stock>0?`In Stock (${p.stock})`:'Out of Stock'}</b></div></div><div style={{display:'flex',gap:7,flexWrap:'wrap',justifyContent:'flex-end'}}><button onClick={()=>setEditing({id:p.id,name:p.name,editPrice:p.price,editStock:p.stock})}>Edit Price/Stock</button><button onClick={()=>del(p.id)}>Delete</button></div></div>)}</section>
{editing&&<section style={box}><h2>Edit: {editing.name}</h2><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><label>Price ₹<input type="number" step="0.01" value={editing.editPrice} onChange={e=>setEditing({...editing,editPrice:e.target.value})}/></label><label>Stock Qty<input type="number" min="0" value={editing.editStock} onChange={e=>setEditing({...editing,editStock:e.target.value})}/></label><button disabled={saving} onClick={()=>save(editing)}>Save</button><button onClick={()=>setEditing(null)}>Cancel</button></div></section>}
<section style={box}><h2>Add New Product</h2><form onSubmit={add} style={{display:'grid',gap:12}}><input name="name" placeholder="Product Name" required/><input name="price" type="number" step="0.01" min="0" placeholder="Price ₹" required/><input name="stock" type="number" min="0" placeholder="Stock Quantity" defaultValue="0" required/><input type="file" accept="image/*" onChange={upload} disabled={uploading} required/>{uploadedImageUrl&&<img src={uploadedImageUrl} alt="Preview" style={{width:120,height:120,objectFit:'contain'}}/>}<textarea name="description" rows="3" placeholder="Description"/><button type="submit" disabled={uploading||saving||!uploadedImageUrl}>{saving?'Saving…':'Add Product'}</button></form></section></main></div>}
createRoot(document.getElementById('admin-root')).render(<Admin/>);