import React,{useEffect,useState}from'react';
import { supabase } from './supabase';

export function AuthPage(){
 const [mode,setMode]=useState('login'); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [name,setName]=useState(''); const [loading,setLoading]=useState(false); const [message,setMessage]=useState('');
 const submit=async e=>{e.preventDefault();setLoading(true);setMessage('');try{const result=mode==='login'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password,options:{data:{full_name:name},emailRedirectTo:window.location.origin+'/'}});if(result.error){setMessage(result.error.message);return;}if(mode==='login'){setMessage('Login successful. Redirecting…');window.location.replace('/');}else if(result.data?.session){setMessage('Account created successfully. Redirecting…');window.location.replace('/');}else{setMessage('Account created! Please check your email and click the confirmation link to finish signing in.');}}catch(err){setMessage(err?.message||'Something went wrong. Please try again.');}finally{setLoading(false);}};
 return <main className="auth-page"><div className="auth-glow auth-glow-one"/><div className="auth-glow auth-glow-two"/><section className="auth-shell"><aside className="auth-showcase"><div className="auth-brand-mark">ॐ</div><div className="auth-eyebrow">POOJAN PARADISE</div><h2>Pure devotion.<br/><em>Premium essentials.</em></h2><p>Shop thoughtfully selected pooja essentials, crafted for every sacred moment.</p><div className="auth-trust"><span>✦</span> Premium Quality <span>•</span> Trusted Service <span>•</span> Secure Account</div></aside><div className="auth-card"><div className="auth-mobile-brand"><span>ॐ</span><b>POOJAN PARADISE</b></div><div className="auth-tabs"><button className={mode==='login'?'active':''} onClick={()=>{setMode('login');setMessage('')}}>Login</button><button className={mode==='register'?'active':''} onClick={()=>{setMode('register');setMessage('')}}>Sign Up</button></div><div className="auth-heading"><span className="auth-kicker">WELCOME TO POOJAN PARADISE</span><h1>{mode==='login'?'Welcome back':'Create your account'}</h1><p>{mode==='login'?'Sign in to continue your premium shopping experience.':'Join us and make every pooja more special.'}</p></div><form onSubmit={submit}>{mode==='register'&&<label>Full name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Enter your full name" autoComplete="name" required/></label>}<label>Email address<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" autoComplete="email" required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Minimum 6 characters" minLength="6" autoComplete={mode==='login'?'current-password':'new-password'} required/></label><button className="auth-submit" disabled={loading}>{loading?'Please wait…':mode==='login'?'Sign In':'Create Account'} <span>→</span></button></form>{message&&<div className="auth-message">{message}</div>}<div className="auth-switch-row">{mode==='login'?<>New to Poojan Paradise? <button onClick={()=>{setMode('register');setMessage('')}}>Create an account</button></>:<>Already have an account? <button onClick={()=>{setMode('login');setMessage('')}}>Sign in</button></>}</div><a className="auth-home" href="/">← Back to Poojan Paradise</a><small className="auth-secure">🔒 Your account information is securely handled.</small></div></section></main>;
}

export function useSession(){const [session,setSession]=useState(null);useEffect(()=>{let mounted=true;supabase.auth.getSession().then(({data})=>mounted&&setSession(data.session));const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,s)=>setSession(s));return()=>{mounted=false;subscription.unsubscribe()};},[]);return session;}
